MingBlog/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls')),
    url(r'', include('comments.urls')),
]

blog/urls.py
#coding:utf-8

from django.conf.urls import url

from . import views
#命名空间
app_name = 'blog'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.detail, name='detail'),
    url(r'^archives/$', views.archives, name='archives'),
    url(r'^about/$', views.about, name='about'),
]

comments/urls.py

from django.conf.urls import url

from . import views

app_name = 'comments'
urlpatterns = [
    url(r'^comment/post/(?P<post_pk>[0-9]+)/$', views.post_comment, name='post_comment'),
]

blog/models.py
#coding:utf-8
import markdown
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.six import python_2_unicode_compatible
from django.utils.html import strip_tags


# Create your models here.
#分类模型
@python_2_unicode_compatible
class Category(models.Model):
    name = models.CharField(max_length=100)
    def __str__(self):
        return self.name
    
#标签模型
@python_2_unicode_compatible
class Tag(models.Model):
    name = models.CharField(max_length=100)
    def __str__(self):
        return self.name

#文章模型
@python_2_unicode_compatible
class Post(models.Model):
    #文章标题
    title = models.CharField(max_length=70)
    #文章正文
    body = models.TextField()
    #文章创建时间
    created_time = models.DateTimeField()
    #文章修改时间
    modified_time = models.DateTimeField()
    #文章摘要,允许空值
    excerpt = models.CharField(max_length=200, blank=True)
    #文章分类，使用外键与Category模型联系
    category = models.ForeignKey(Category)
    #文章标签,文章与标签是多对多关系，且允许为空
    tags = models.ManyToManyField(Tag, blank=True)
    # 新增 views 字段记录阅读量
    views = models.PositiveIntegerField(default=0)
    #文章作者，使用外键与User模型（自有）联系起来,注意在文件头部导入User模型
    author = models.ForeignKey(User)
    def __str__(self):
        return self.title
    #自定义get_absolute_url方法
    #注意头部导入reverse函数
    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'pk': self.pk})
    #阅读数量字段的方法
    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])
    #文章摘要的方法
    def save(self, *args, **kwargs):    
        # 如果没有填写摘要
        if not self.excerpt:
            # 首先实例化一个 Markdown 类，用于渲染 body 的文本
            md = markdown.Markdown(extensions=[
                'markdown.extensions.extra',
                'markdown.extensions.codehilite',
            ])
            # 先将 Markdown 文本渲染成 HTML 文本
            # strip_tags 去掉 HTML 文本的全部 HTML 标签
            # 从文本摘取前 54 个字符赋给 excerpt
            self.excerpt = strip_tags(md.convert(self.body))[:54]

        # 调用父类的 save 方法将数据保存到数据库中
        super(Post, self).save(*args, **kwargs)

    class Meta:
        ordering = ['-created_time']

    

comments/models.py
#coding:utf-8
from django.db import models
from django.utils.six import python_2_unicode_compatible

# python_2_unicode_compatible 装饰器用于兼容 Python2
@python_2_unicode_compatible
class Comment(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=255)
    url = models.URLField(blank=True)
    text = models.TextField()
    created_time = models.DateTimeField(auto_now_add=True)

    post = models.ForeignKey('blog.Post')

    def __str__(self):
        return self.text[:20]

comments/forms.py

from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'url', 'text']

blog/views.py
#coding:utf-8
import markdown
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from comments.forms import CommentForm
from .models import Post, Category

def index(request):
    post_list = Post.objects.all().order_by('-created_time')
    return render(request, 'blog/index.html', context={'post_list': post_list})

#文章详情的视图
def detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    # 阅读量 +1
    post.increase_views()
    post.body = markdown.markdown(post.body,
                                  extensions=[
                                      'markdown.extensions.extra',
                                      'markdown.extensions.codehilite',
                                      'markdown.extensions.toc',
                                  ])
    # 记得在顶部导入 CommentForm
    form = CommentForm()
    # 获取这篇 post 下的全部评论
    comment_list = post.comment_set.all()

    # 将文章、表单、以及文章下的评论列表作为模板变量传给 detail.html 模板，以便渲染相应数据。
    context = {'post': post,
               'form': form,
               'comment_list': comment_list
               }
    return render(request, 'blog/detail.html', context=context)

def archives(request):
    post_list = Post.objects.all().order_by('-created_time')
    return render(request, 'blog/archives.html', context={'post_list': post_list})

def about(request):
    return render(request, 'blog/about.html')

   

comments/views.py
#coding:utf-8
from django.shortcuts import render, get_object_or_404, redirect
from blog.models import Post

from .models import Comment
from .forms import CommentForm


def post_comment(request, post_pk):
    # 先获取被评论的文章，因为后面需要把评论和被评论的文章关联起来。
    # 这里我们使用了 Django 提供的一个快捷函数 get_object_or_404，
    # 这个函数的作用是当获取的文章（Post）存在时，则获取；否则返回 404 页面给用户。
    post = get_object_or_404(Post, pk=post_pk)

    # HTTP 请求有 get 和 post 两种，一般用户通过表单提交数据都是通过 post 请求，
    # 因此只有当用户的请求为 post 时才需要处理表单数据。
    if request.method == 'POST':
        # 用户提交的数据存在 request.POST 中，这是一个类字典对象。
        # 我们利用这些数据构造了 CommentForm 的实例，这样 Django 的表单就生成了。
        form = CommentForm(request.POST)

        # 当调用 form.is_valid() 方法时，Django 自动帮我们检查表单的数据是否符合格式要求。
        if form.is_valid():
            # 检查到数据是合法的，调用表单的 save 方法保存数据到数据库，
            # commit=False 的作用是仅仅利用表单的数据生成 Comment 模型类的实例，但还不保存评论数据到数据库。
            comment = form.save(commit=False)

            # 将评论和被评论的文章关联起来。
            comment.post = post

            # 最终将评论数据保存进数据库，调用模型实例的 save 方法
            comment.save()

            # 重定向到 post 的详情页，实际上当 redirect 函数接收一个模型的实例时，它会调用这个模型实例的 get_absolute_url 方法，
            # 然后重定向到 get_absolute_url 方法返回的 URL。
            return redirect(post)

        else:
            # 检查到数据不合法，重新渲染详情页，并且渲染表单的错误。
            # 因此我们传了三个模板变量给 detail.html，
            # 一个是文章（Post），一个是评论列表，一个是表单 form
            # 注意这里我们用到了 post.comment_set.all() 方法，
            # 这个用法有点类似于 Post.objects.all()
            # 其作用是获取这篇 post 下的的全部评论，
            # 因为 Post 和 Comment 是 ForeignKey 关联的，
            # 因此使用 post.comment_set.all() 反向查询全部评论。
            # 具体请看下面的讲解。
            comment_list = post.comment_set.all()
            context = {'post': post,
                       'form': form,
                       'comment_list': comment_list
                       }
            return render(request, 'blog/detail.html', context=context)
    # 不是 post 请求，说明用户没有提交数据，重定向到文章详情页。
    return redirect(post)

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<!-- saved from url=(0042)https://lixianhua.com/temenu_document.html -->
<html class="no-js"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="renderer" content="webkit">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <title>文章详情</title>

    <link href="{% static 'blog/img/favicon.ico' %}" rel="icon">
    <link rel="stylesheet" href="{% static 'blog/css/icon.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/global.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/markdown.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/font_m7mp27xfc0jp2e29.css' %}">
        <!--[if lt IE 9]>
    <script src="//cdnjscn.b0.upaiyun.com/libs/html5shiv/r29/html5.min.js"></script>
    <script src="//cdnjscn.b0.upaiyun.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
    <meta name="description" content="文章存档">

	<style type="text/css">
			/* Code tidied up by ScrapBook */
			#te-cmt-tool { display: none; list-style: outside none none; padding: 0px; margin: 10px 0px; }
			#te-cmt-cmd { padding: 0px; margin: 0px; overflow: hidden; list-style: outside none none; border: 1px solid rgb(150, 150, 150); border-radius: 3px; }
			#te-cmt-cmd li { padding: 0px; margin: 0px; float: left; border: medium none; }
			#te-cmt-cmd li a { height: 32px; line-height: 32px; padding: 0px 10px; display: block; }
			.te-cmt-smilies { display: none; padding: 8px 5px 5px; margin-top: -3px; border-width: medium 1px 1px; border-style: none solid solid; border-color: currentcolor rgb(150, 150, 150) rgb(150, 150, 150); -moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; border-image: none; border-radius: 0px 0px 3px 3px; }
			.te-cmt-smilies span { cursor: pointer; }
			.te-cmt-smilies span img { vertical-align: middle; }
			.te-cmt-ban { height: 20px; line-height: 20px; }
			.te-cmt-ban input[type="checkbox"] { margin: 0px; padding: 0px; vertical-align: middle; }
    </style>
	<script src="{% static 'blog/js/hm.js' %}"></script>
	<script src="{% static 'blog/js/share.js' %}"></script>
<body>
<div id="wrapper" class="single">
    <header id="header" style="top: 0px;">
		<a class="site-name" href="#" title="芒果浩明的个人博客">明</a>
        <nav class="nav">
             <a href="{% url 'blog:index' %}" title="首页"><i class="icon icon-home"></i> <span>首页</span></a>
            <a href="{% url 'blog:archives' %}" title="归档"><i class="icon icon-archive"></i> <span>归档</span></a>
            <a href="#" title="标签"><i class="icon icon-tag"></i> <span>标签</span></a>
            <a href="#" title="链接"><i class="icon icon-cat"></i> <span>分类</span></a>
            <a href="#" title="留言"><i class="icon icon-comment"></i> <span>留言</span></a>
            <a href="{% url 'blog:about' %}" title="关于"><i class="icon icon-info"></i> <span>关于</span></a>          
        </nav>
    </header>
    
    <div id="body">
        <div class="body-header" style="top: 0px;">
			<a href="https://lixianhua.com/temenu_document.html#" class="btn btn-default btn-nav-size pull-left hidden-xs"><i class="icon icon-outdent"></i></a>
			<a href="https://lixianhua.com/temenu_document.html#" class="btn btn-default btn-screen-size pull-left hidden-xs"><i class="icon icon-compress"></i></a>
			<div class="site-search pull-left">
                <form id="search" class="form" method="post" action="https://lixianhua.com/" role="search">
                    <label for="s" class="sr-only">搜索关键字</label>
                    <input type="text" name="s" class="form-control" placeholder="搜索">
                    <button type="submit" class="btn btn-default" title="搜索"><i class="icon icon-search"></i></button>
                </form>
            </div>
							<a href="https://lixianhua.com/admin/login.php" class="btn btn-default pull-right" title="登录"><i class="icon icon-login"></i></a>
			            <a href="https://lixianhua.com/temenu_document.html#" class="btn btn-default btn-mode pull-right"><i class="icon icon-moon"></i></a>
        </div>
        <div id="main">
			 {% block main %}
    		 {% endblock main %}
		</div>
	</div><!-- end #main-->
		
<footer class="footer">
	<div class="footer-inner">
				<p><a href="{% url 'blog:archives' %}"><i class=""></i> 归档 </a>
				   <a href="#"><i class=""></i> 标签 </a>
				   <a href="#"><i class=""></i> 链接 </a>
				   <a href="#"><i class=""></i> 留言 </a>
				   <a href="{% url 'blog:about' %}"><i class=""></i> 关于 </a>
				 </p>
				<p>© 2017 <a href="#">芒果浩明</a>
					<em>·</em> <a href="http://www.typecho.org/" target="_blank">Typecho</a>
					 <span class="hidden-xs"><em>·</em> <a href="http://www.miitbeian.gov.cn/" target="blank">备案号</a></span>					<em>·</em> Theme By <a href="http://whaoming.site" target="_blank">绛木子由芒果浩明修改</a>
			    </p>
			</div>
</footer><!-- end #footer -->
    </div>
	<div class="site-tool">
		<a href="https://lixianhua.com/temenu_document.html#" class="icon icon-top btn-gotop" style="display: none;"></a>
	</div>
</div><!-- end #wrapper -->
<script src="{% static 'blog/js/hm.js' %}"></script>
<script src="{% static 'blog/js/jquery.min.js' %}"></script>
<script src="{% static 'blog/js/jquery.plugins.js' %}"></script>
<script src="{% static 'blog/js/app.js' %}"></script>
<script src="{% static 'blog/js/collect.js' %}"></script>
<script>!window.jQuery && document.write("<script src=\"https://apps.bdimg.com/libs/jquery/1.11.1/jquery.min.js\">"+"</scr"+"ipt>");</script>
<script src="{% static 'blog/js/tecomment.js' %}"></script>
<div id="pjax-loading" style="width: 0px; display: none;"></div>

</body>
</html>

templates/blog/about.html
{% extends 'base.html' %}
{% load staticfiles %}
 {% block main %}
 <article class="post page">
	<h1 class="post-title">关于</h1>
	<div class="post-content markdown">
		<div class="archives">
        
    </article>

{% endblock main %}

templates/blog/detail.html
{% extends 'base.html' %}
{% load staticfiles %}
 {% block main %}
	<h1 class="post-title">{{ post.title }}</h1>
	<div class="post-author">
		<a href="#" class="avatar pull-left"><img src="#" alt=""></a>
		<div class="post-author-info">
			<p><span class="tag">{{ post.category }}</span> <a class="author-name" href="https://lixianhua.com/author/1/">{{ post.author }}</a></p>
			<p class="post-meta">
				<span datetime="{{ post.created_time }}" title="2017-08-24 18:33:00">{{ post.created_time }}</span>
				<span>阅读 {{ post.views }}</span>
				<span>评论 {{ post.comment_set.count }}</span>
				<span>喜欢 0</span>
			</p>
		</div>
	</div>
	<div class="post-content markdown">
		{{ post.body|safe }}
	</div>
	<div class="post-foot">
		<span class="post-tags"><i class="icon icon-tag"></i> <a href="https://lixianhua.com/category/doc/">文档</a> <a href="https://lixianhua.com/tag/TeMenu/">TeMenu</a> <a href="https://lixianhua.com/tag/%E8%8F%9C%E5%8D%95/">菜单</a></span>
		<span class="pull-right" title="转载请注明出处">© 著作权归作者所有</span>
	</div>
	<div class="post-tool">
		<div class="social">
			<div class="social-inner">
				<a class="social-left btn-like" href="https://lixianhua.com/temenu_document.html#" data-cid="55"><i class="icon icon-like"></i> 点赞 <span class="likes-num">0</span></a>
				<div class="social-round">
					<div class="social-round-border"><span></span></div>
					<a class="social-round-inner" href="https://lixianhua.com/temenu_document.html#">赏												<div class="donate">
							<h4><i class="icon icon-donate"></i> 如果认为本文对您有所帮助请赞助本站</h4>
							<div class="donate-item">
																<div><img src="./detail_files/alipay.png" alt="alipay"><h5>支付宝扫一扫赞助</h5></div>
																							</div>
						</div>
											</a>
				</div>
				<div class="social-right share" href="#"><i class="icon icon-share"></i> 分享					<div class="share-list">
						<div class="bdsharebuttonbox">
							<a href="https://lixianhua.com/temenu_document.html#" class="bds_more" data-cmd="more"></a>
							<a href="https://lixianhua.com/temenu_document.html#" class="bds_weixin" data-cmd="weixin" title="分享到微信"></a>
							<a href="https://lixianhua.com/temenu_document.html#" class="bds_sqq" data-cmd="sqq" title="分享到QQ好友"></a>
							<a href="https://lixianhua.com/temenu_document.html#" class="bds_tsina" data-cmd="tsina" title="分享到新浪微博"></a>
							<a href="https://lixianhua.com/temenu_document.html#" class="bds_mail" data-cmd="mail" title="分享到邮件分享"></a>
							<a href="https://lixianhua.com/temenu_document.html#" class="bds_copy" data-cmd="copy" title="分享到复制网址"></a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</article>
<div id="comments">
	 <section class="comment-area" id="comment-area">
                    <hr>
                    <h3>发表评论</h3>
                    <form action="{% url 'comments:post_comment' post.pk %}" method="post" class="comment-form">
                      {% csrf_token %}
                      <div class="row">
                        <div class="col-md-4">
                          <label for="{{ form.name.id_for_label }}">名字：</label>
                          {{ form.name }}
                          {{ form.name.errors }}
                        </div>
                        <div class="col-md-4">
                          <label for="{{ form.email.id_for_label }}">邮箱：</label>
                          {{ form.email }}
                          {{ form.email.errors }}
                        </div>
                        <div class="col-md-4">
                          <label for="{{ form.url.id_for_label }}">URL：</label>
                          {{ form.url }}
                          {{ form.url.errors }}
                        </div>
                        <div class="col-md-12">
                          <label for="{{ form.text.id_for_label }}">评论：</label>
                          {{ form.text }}
                          {{ form.text.errors }}
                          <button type="submit" class="comment-btn">发表</button>
                        </div>
                      </div>    <!-- row -->
                    </form>
                    <div class="comment-list-panel">
                        <h3>评论列表，共 <span>4</span> 条评论</h3>
                        <ul class="comment-list list-unstyled">
                          {% for comment in comment_list %}
                          <li class="comment-item">
                            <span class="nickname">{{ comment.name }}</span>
                            <time class="submit-date">{{ comment.created_time }}</time>
                            <div class="text">
                              {{ comment.text }}
                            </div>
                          </li>
                          {% empty %}
                          暂无评论
                          {% endfor %}
                        </ul>
                    </div>
       </section>
 </div>
{% endblock main %}

templates/blog/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html class="no-js">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="renderer" content="webkit">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <title>芒果浩明</title>

    <link href="{% static 'blog/img/favicon.ico' %}" rel="icon">
    <link rel="stylesheet" href="{% static 'blog/css/icon.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/global.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/markdown.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/font_m7mp27xfc0jp2e29.css' %}">
        <!--[if lt IE 9]>
    <script src="//cdnjscn.b0.upaiyun.com/libs/html5shiv/r29/html5.min.js"></script>
    <script src="//cdnjscn.b0.upaiyun.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
    
    <style type="text/css">
			/* Code tidied up by ScrapBook */
			#te-cmt-tool { display: none; list-style: outside none none; padding: 0px; margin: 10px 0px; }
			#te-cmt-cmd { padding: 0px; margin: 0px; overflow: hidden; list-style: outside none none; border: 1px solid rgb(150, 150, 150); border-radius: 3px; }
			#te-cmt-cmd li { padding: 0px; margin: 0px; float: left; border: medium none; }
			#te-cmt-cmd li a { height: 32px; line-height: 32px; padding: 0px 10px; display: block; }
			.te-cmt-smilies { display: none; padding: 8px 5px 5px; margin-top: -3px; border-width: medium 1px 1px; border-style: none solid solid; border-color: currentcolor rgb(150, 150, 150) rgb(150, 150, 150); -moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; border-image: none; border-radius: 0px 0px 3px 3px; }
			.te-cmt-smilies span { cursor: pointer; }
			.te-cmt-smilies span img { vertical-align: middle; }
			.te-cmt-ban { height: 20px; line-height: 20px; }
			.te-cmt-ban input[type="checkbox"] { margin: 0px; padding: 0px; vertical-align: middle; }
    </style>
	<script src="{% static 'blog/js/hm.js' %}"></script>
	<script src="{% static 'blog/js/share.js' %}"></script>
</head>
<body>
<div id="wrapper" class="">
    <header id="header" style="top: 0px;">
		<a class="site-name" href="#" title="芒果浩明的个人博客">明</a>
        <nav class="nav">
            <a href="{% url 'blog:index' %}" title="首页"><i class="icon icon-home"></i> <span>首页</span></a>
            <a href="{% url 'blog:archives' %}" title="归档"><i class="icon icon-archive"></i> <span>归档</span></a>
            <a href="tags.html" title="标签"><i class="icon icon-tag"></i> <span>标签</span></a>
            <a href="#" title="链接"><i class="icon icon-link"></i> <span>链接</span></a>
            <a href="#" title="留言"><i class="icon icon-comment"></i> <span>留言</span></a>
            <a href="{% url 'blog:about' %}" title="关于"><i class="icon icon-info"></i> <span>关于</span></a>        
        </nav>
    </header>
    <div id="cover" style="background-image: url(&quot;{% static 'blog/img/bg.jpg' %}&quot;);">
		<div class="cover-info">
            <img src="{% static 'blog/img/avatar.jpg' %}" alt="芒果浩明" class="avatar">
            			<h1>芒果浩明</h1>
			<p>芒果浩明的个人博客</p>
			<div class="follow-me">
			   <a href="https://github.com/IHaoMing" class="icon icon-github" target="_blank"></a>
		    </div>
		</div>
	</div>
    <div id="body">
        <div class="body-header" style="top: 0px;">
			<a href="#" class="btn btn-default btn-nav-size pull-left hidden-xs"><i class="icon icon-outdent"></i></a>
			<a href="#" class="btn btn-default btn-screen-size pull-left hidden-xs"><i class="icon icon-compress"></i></a>
			<div class="site-search pull-left">
                <form id="search" class="form" method="post" action="https://lixianhua.com/" role="search">
                    <label for="s" class="sr-only">搜索关键字</label>
                    <input name="s" class="form-control" placeholder="搜索" type="text">
                    <button type="submit" class="btn btn-default" title="搜索"><i class="icon icon-search"></i></button>
                </form>
            </div>
							<a href="#" class="btn btn-default pull-right" title="登录"><i class="icon icon-login"></i></a>
			            <a href="#" class="btn btn-default btn-mode pull-right"><i class="icon icon-moon"></i></a>
        </div>
    <div id="main">			<div id="banner" class="carousel slide" data-ride="carousel" data-interval="5000" data-multi="true">
		<a class="left carousel-control" href="#banner" role="button" data-slide="prev">
			<span class="icon icon-prev" aria-hidden="true"></span>
			<span class="sr-only">Previous</span>
		</a>
		<a class="right carousel-control" href="#banner" role="button" data-slide="next">
			<span class="icon icon-next" aria-hidden="true"></span>
			<span class="sr-only">Next</span>
		</a>
	</div>
	<div class="post-list">
		
			
		{% for post in post_list %}
		  <article class="post post-{{ post.pk }}">
		    <div class="post-wrap">
			<div class="post-author">
				<a href="#" class="avatar"><img src="{% static 'blog/img/tx.jpeg' %}" alt=""></a>
				<a class="author-name" href="#">{{ post.author }}</a>
				<span datetime="{{ post.created_time }}" itemprop="datePublished">{{ post.created_time }}</span>
			</div>
			<a class="post-title" href="{{ post.get_absolute_url }}">{{ post.title }}</a>
			<div class="post-abstract">
				{{ post.excerpt }}
			</div>
			<ul class="post-meta">
				<li class="cat"><a href="#">{{ post.category.name }}</a></li>
				<li><a href="#"><i class="icon icon-tag"></i></a></li>
				<li><a href="{{ post.get_absolute_url }}"><i class="icon icon-eye"></i>{{ post.views }}</a></li>
				<li><a href="#"><i class="icon icon-comment"></i>{{ post.comment_set.count }} </a></li>
				<li><i class="icon icon-like"></i> 20</li>
				<li></li>
			</ul>
		</div>
		  </article>
		{% empty %}
		  <div class="no-post">暂时还没有发布的文章！</div>
		{% endfor %}
	</div>
<!-- 分页 -->
<ol class="page-navigator"><li class="current"><a href="https://lixianhua.com/page/1/">1</a></li><li><a href="https://lixianhua.com/page/2/">2</a></li><li class="next"><a href="https://lixianhua.com/page/2/">后一页 »</a></li></ol>

<div class="hidden"><script>
var _hmt = _hmt || [];
(function() {
  var hm = document.createElement("script");
  hm.src = "https://hm.baidu.com/hm.js?3250a196b4edbd5ceebbc6b1483c6c38";
  var s = document.getElementsByTagName("script")[0]; 
  s.parentNode.insertBefore(hm, s);
})();
</script></div>
</div><!-- end #main-->


<footer class="footer">
	<div class="footer-inner">
				<p><a href="#"><i class=""></i> 归档 </a>
				   <a href="#"><i class=""></i> 标签 </a>
				   <a href="#"><i class=""></i> 链接 </a>
				   <a href="#"><i class=""></i> 留言 </a>
				   <a href="#"><i class=""></i> 关于 </a>
				 </p>
				<p>© 2017 <a href="#">芒果浩明</a>
					<em>·</em> <a href="http://www.typecho.org/" target="_blank">Typecho</a>
					 <span class="hidden-xs"><em>·</em> <a href="http://www.miitbeian.gov.cn/" target="blank">备案号</a></span>					<em>·</em> Theme By <a href="http://whaoming.site" target="_blank">绛木子由芒果浩明修改</a>
			    </p>
			</div>
</footer><!-- end #footer -->

    </div>
	<div class="site-tool">
		<a href="#" class="icon icon-top btn-gotop" style="display: none;"></a>
	</div>
</div><!-- end #wrapper -->
<script src="{% static 'blog/js/jquery.min.js' %}"></script>
<script src="{% static 'blog/js/jquery.plugins.js' %}"></script>
<script src="{% static 'blog/js/app.js' %}"></script>

<!--缩放-->
<script src="{% static 'blog/js/collect.js' %}"></script>
</body>
</html>